tag-template: v$NEXT_PATCH_VERSION
name-template: v$NEXT_PATCH_VERSION 🎁

version-template: "$MAJOR.$MINOR.$PATCH"

template: |
  ## Changes

  $CHANGES


categories:
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
  - title: 🐳 Docker updates
    label: docker-update
  - title: ⛓️‍💥 Breaking changes
    label: breaking
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: 📖 Documentation updates
    label: documentation
  - title: 🚨 Removed / ⚠️ Deprecated
    labels:
      - removed
      - deprecated
  - title: 🚦 Tests and Infrastructure
    labels:
      - tests
      - infrastructure
    collapse-after: 10
  - title: 🔨 Dependency updates
    labels:
      - dependencies
      - dependency
    collapse-after: 10

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
  - search: '/HTM-(\d+)/g'
    replace: '[HTM-$1](https://b3partners.atlassian.net/browse/HTM-$1)'
