tag-template: v$NEXT_PATCH_VERSION
name-template: v$NEXT_PATCH_VERSION 🎁

version-template: "$MAJOR.$MINOR.$PATCH"

template: |
  ## Changes

  $CHANGES


categories:
  - title: 🚀 New features and improvements
    when:
      labels:
        - enhancement
        - feature
        - refactoring
        - Accessibility
  - title: 🐳 Docker updates
    when:
      label: docker-update
  - title: ⛓️‍💥 Breaking changes
    when:
      label: breaking
  - title: 🐛 Bug Fixes
    when:
      labels:
        - bug
        - fix
        - bugfix
        - regression
  - title: 📖 Documentation updates
    when:
      labels:
        - documentation
  - title: 🚨 Removed / ⚠️ Deprecated
    when:
      labels:
        - removed
        - deprecated
  - title: 🚦 Tests and Infrastructure
    when:
      labels:
        - tests
        - infrastructure
    collapse-after: 10
  - title: 🔨 Dependency updates
    when:
      labels:
        - dependencies
        - dependency
    collapse-after: 10

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
  - search: '/HTM-(\d+)/g'
    replace: '[HTM-$1](https://b3partners.atlassian.net/browse/HTM-$1)'
  - search: '/EK-(\d+)/g'
    replace: '[EK-$1](https://b3partners.atlassian.net/browse/EK-$1)'
  - search: '/EO-(\d+)/g'
    replace: '[EO-$1](https://b3partners.atlassian.net/browse/EO-$1)'
