tag-template: v$NEXT_PATCH_VERSION
name-template: v$NEXT_PATCH_VERSION 🎁

version-template: "$MAJOR.$MINOR.$PATCH"

template: |
  ## What’s Changed

  $CHANGES


categories:
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
  - title: ⛓️‍💥 Breaking changes
    label: breaking
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: 📖 Documentation updates
    label: documentation
  - title: 🚨 Removed / ⚠️ Deprecated
    labels: 
      - removed
      - deprecated
  - title: 🚦 Tests and Infrastructure
    labels:
      - tests
      - infrastructure
  - title: 🔨 Dependency updates
    labels: 
      - dependencies
      - dependency

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
