// Regenerate bookmark_pb.ts by using `npm run generate-protobuf`

// @generated by protoc-gen-es v1.1.1 with parameter "target=ts"
// @generated from file bookmark.proto (package bookmark, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum bookmark.TristateBoolean
 */
export enum TristateBoolean {
  /**
   * @generated from enum value: UNSET = 0;
   */
  UNSET = 0,

  /**
   * @generated from enum value: FALSE = 1;
   */
  FALSE = 1,

  /**
   * @generated from enum value: TRUE = 2;
   */
  TRUE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(TristateBoolean)
proto3.util.setEnumType(TristateBoolean, "bookmark.TristateBoolean", [
  { no: 0, name: "UNSET" },
  { no: 1, name: "FALSE" },
  { no: 2, name: "TRUE" },
]);

/**
 * The bookmark fragments which protobuf data. Because fragments may use long strings to refer to the same app layer or node ids, these are
 * combined in this message and compressed once instead of compressed separately
 *
 * @generated from message bookmark.BinaryBookmarkFragments
 */
export class BinaryBookmarkFragments extends Message<BinaryBookmarkFragments> {
  /**
   * Versioning to allow for backwards compatibility for old bookmarks, set to 1 currently
   *
   * @generated from field: uint32 version = 1;
   */
  version = 0;

  /**
   * @generated from field: repeated bookmark.BookmarkFragment fragments = 3;
   */
  fragments: BookmarkFragment[] = [];

  constructor(data?: PartialMessage<BinaryBookmarkFragments>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bookmark.BinaryBookmarkFragments";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "version", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "fragments", kind: "message", T: BookmarkFragment, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BinaryBookmarkFragments {
    return new BinaryBookmarkFragments().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BinaryBookmarkFragments {
    return new BinaryBookmarkFragments().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BinaryBookmarkFragments {
    return new BinaryBookmarkFragments().fromJsonString(jsonString, options);
  }

  static equals(a: BinaryBookmarkFragments | PlainMessage<BinaryBookmarkFragments> | undefined, b: BinaryBookmarkFragments | PlainMessage<BinaryBookmarkFragments> | undefined): boolean {
    return proto3.util.equals(BinaryBookmarkFragments, a, b);
  }
}

/**
 * @generated from message bookmark.BookmarkFragment
 */
export class BookmarkFragment extends Message<BookmarkFragment> {
  /**
   * The identifier of BookmarkFragmentDescriptor
   *
   * @generated from field: string identifier = 1;
   */
  identifier = "";

  /**
   * Wrapped protobuf
   *
   * @generated from field: bytes bytes = 2;
   */
  bytes = new Uint8Array(0);

  constructor(data?: PartialMessage<BookmarkFragment>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bookmark.BookmarkFragment";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "identifier", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "bytes", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BookmarkFragment {
    return new BookmarkFragment().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BookmarkFragment {
    return new BookmarkFragment().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BookmarkFragment {
    return new BookmarkFragment().fromJsonString(jsonString, options);
  }

  static equals(a: BookmarkFragment | PlainMessage<BookmarkFragment> | undefined, b: BookmarkFragment | PlainMessage<BookmarkFragment> | undefined): boolean {
    return proto3.util.equals(BookmarkFragment, a, b);
  }
}

/**
 * Represents differences in layer visibility from the default configuration.
 *
 * @generated from message bookmark.LayerVisibilityBookmarkFragment
 */
export class LayerVisibilityBookmarkFragment extends Message<LayerVisibilityBookmarkFragment> {
  /**
   * @generated from field: repeated bookmark.LayerInformation layers = 1;
   */
  layers: LayerInformation[] = [];

  constructor(data?: PartialMessage<LayerVisibilityBookmarkFragment>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bookmark.LayerVisibilityBookmarkFragment";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "layers", kind: "message", T: LayerInformation, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LayerVisibilityBookmarkFragment {
    return new LayerVisibilityBookmarkFragment().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LayerVisibilityBookmarkFragment {
    return new LayerVisibilityBookmarkFragment().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LayerVisibilityBookmarkFragment {
    return new LayerVisibilityBookmarkFragment().fromJsonString(jsonString, options);
  }

  static equals(a: LayerVisibilityBookmarkFragment | PlainMessage<LayerVisibilityBookmarkFragment> | undefined, b: LayerVisibilityBookmarkFragment | PlainMessage<LayerVisibilityBookmarkFragment> | undefined): boolean {
    return proto3.util.equals(LayerVisibilityBookmarkFragment, a, b);
  }
}

/**
 * @generated from message bookmark.LayerInformation
 */
export class LayerInformation extends Message<LayerInformation> {
  /**
   * The ID of this layer
   *
   * @generated from field: string app_layer_id = 4;
   */
  appLayerId = "";

  /**
   * the new visibility state of the layer.
   *
   * note: this is a tristate value, as all values in protobuf are optional,
   * and will default to `false` otherwise.
   *
   * @generated from field: bookmark.TristateBoolean visible = 2;
   */
  visible = TristateBoolean.UNSET;

  /**
   * The opacity of the layer, in percent (0-100, represented as 1-101).
   * If this value is 0, the layer-default opacity is used. A value of 1 maps to 0%,
   * etc.
   *
   * @generated from field: uint32 opacity = 3;
   */
  opacity = 0;

  constructor(data?: PartialMessage<LayerInformation>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bookmark.LayerInformation";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 4, name: "app_layer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "visible", kind: "enum", T: proto3.getEnumType(TristateBoolean) },
    { no: 3, name: "opacity", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LayerInformation {
    return new LayerInformation().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LayerInformation {
    return new LayerInformation().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LayerInformation {
    return new LayerInformation().fromJsonString(jsonString, options);
  }

  static equals(a: LayerInformation | PlainMessage<LayerInformation> | undefined, b: LayerInformation | PlainMessage<LayerInformation> | undefined): boolean {
    return proto3.util.equals(LayerInformation, a, b);
  }
}

/**
 * The (changed) ordering of children in a layer tree
 *
 * @generated from message bookmark.LayerTreeOrderBookmarkFragment
 */
export class LayerTreeOrderBookmarkFragment extends Message<LayerTreeOrderBookmarkFragment> {
  /**
   * @generated from field: map<string, bookmark.LayerTreeOrderInformation> ordering = 1;
   */
  ordering: { [key: string]: LayerTreeOrderInformation } = {};

  constructor(data?: PartialMessage<LayerTreeOrderBookmarkFragment>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bookmark.LayerTreeOrderBookmarkFragment";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ordering", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: LayerTreeOrderInformation} },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LayerTreeOrderBookmarkFragment {
    return new LayerTreeOrderBookmarkFragment().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LayerTreeOrderBookmarkFragment {
    return new LayerTreeOrderBookmarkFragment().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LayerTreeOrderBookmarkFragment {
    return new LayerTreeOrderBookmarkFragment().fromJsonString(jsonString, options);
  }

  static equals(a: LayerTreeOrderBookmarkFragment | PlainMessage<LayerTreeOrderBookmarkFragment> | undefined, b: LayerTreeOrderBookmarkFragment | PlainMessage<LayerTreeOrderBookmarkFragment> | undefined): boolean {
    return proto3.util.equals(LayerTreeOrderBookmarkFragment, a, b);
  }
}

/**
 * @generated from message bookmark.LayerTreeOrderInformation
 */
export class LayerTreeOrderInformation extends Message<LayerTreeOrderInformation> {
  /**
   * @generated from field: repeated string children = 1;
   */
  children: string[] = [];

  constructor(data?: PartialMessage<LayerTreeOrderInformation>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "bookmark.LayerTreeOrderInformation";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "children", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LayerTreeOrderInformation {
    return new LayerTreeOrderInformation().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LayerTreeOrderInformation {
    return new LayerTreeOrderInformation().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LayerTreeOrderInformation {
    return new LayerTreeOrderInformation().fromJsonString(jsonString, options);
  }

  static equals(a: LayerTreeOrderInformation | PlainMessage<LayerTreeOrderInformation> | undefined, b: LayerTreeOrderInformation | PlainMessage<LayerTreeOrderInformation> | undefined): boolean {
    return proto3.util.equals(LayerTreeOrderInformation, a, b);
  }
}

