name: 'Cleanup and Maintainance'

on:
  workflow_dispatch:
  schedule:
    - cron: '19 17 * * MON'

jobs:
  stale:
    runs-on: ubuntu-latest
    name: 'Close Stale PRs'
    permissions:
      pull-requests: write
    steps:
      - uses: 'actions/stale@v9'
        with:
          days-before-stale: 60
          days-before-close: 10


  workflows:
    runs-on: ubuntu-latest
    name: 'Cleanup old workflow runs'
    permissions:
      actions: write
      contents: read
    steps:
      - uses: 'Mattraks/delete-workflow-runs@v2'
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 90
          keep_minimum_runs: 2


  dockercleanup:
    name: 'Pruning Untagged Images'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: 'Older than 5 days'
        uses: dataaxiom/ghcr-cleanup-action@v1.0.14
        with:
          package: 'tailormap'
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true
          older-than: '5 days'
          log-level: debug
