name: 'Remove deployment'

on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup:
    name: 'Remove Docker Compose deployment'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - name: 'Set variables for PR'
        env:
          PR: ${{ github.event.pull_request.number }}
        run: |
          echo "VERSION_TAG=pr-${PR}" >> $GITHUB_ENV

      - name: 'Log in to GitHub container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ${{ secrets.DOCKER_HOST_SNAPSHOT }}
          context_name: 'dev-server'
          ssh_cert: ${{ secrets.DOCKER_HOST_SNAPSHOT_SSH_CERT }}
          ssh_key: ${{ secrets.DOCKER_HOST_SNAPSHOT_SSH_KEY }}
          use_context: true

      - name: 'Add known hosts'
        run: |
          ssh-keyscan -H ${{ secrets.DOCKER_HOSTNAME }} > $HOME/.ssh/known_hosts

      - name: 'Remove pull request deployment and prune images'
        env:
          COMPOSE_FILE: docker-compose.yml:docker-compose.traefik.yml:ci/docker-compose.pr.yml
          COMPOSE_PROJECT_NAME: tailormap-${{ env.VERSION_TAG }}
          VERSION: ${{ env.VERSION_TAG }}
        run: |
          docker compose down --rmi all --volumes --remove-orphans
          docker image prune --force

      - name: 'Remove GitHub deployment and environment'
        if: ${{ always() }}
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: "${{ secrets.GHCR_CLEANUP_PAT }}"
          environment: "${{ env.VERSION_TAG }}"

